### ISSUE TITLE
Upgrade Redshift Cluster To New DC2 Node Type 

### ISSUE THREAD

**Issue by amw2104** [HearthSim/hsredshift#105]
Should net us 30% improvement in performance with no change in cost, according to the announcement.

NOTE: We need to figure out how to handle our reservations on the DC1 nodes that we are using currently.

https://aws.amazon.com/about-aws/whats-new/2017/10/amazon-redshift-announces-dense-compute-dc2-nodes-with-twice-the-performance-as-dc1-at-the-same-price/

**Comment by beheh** [comment]
Waiting on a reply from AWS.

**Comment by beheh** [comment]
Issue moved to [HearthSim/server-provisioning #120](https://github.com/HearthSim/server-provisioning/issues/120) via [**ZenHub**](https://www.zenhub.com/)
