### ISSUE TITLE
Stop storing casual games and options data

### ISSUE THREAD

**Issue by amw2104** [HearthSim/hsredshift#13]

**Comment by amw2104** [comment]
Also consider no longer storing the Options data until we start using it.

**Comment by jleclanche** [comment]
6661583c83ef26369ea4122f040e14526a4bf8db drops options from the exporter.

**Comment by jleclanche** [comment]
https://github.com/HearthSim/HSReplay.net/commit/dc4d5b66da28cf79169bd64f7dfae918382fa449 adds a whitelist. Closing.
