### ISSUE TITLE
Put hsredshift UDFs on a diet

### ISSUE THREAD

**Issue by beheh** [HearthSim/hsredshift#131]
As an operational stakeholder in the hsredshift reporting framework, I need to ensure that the Python UDFs executed by the framework stay well within the resource limits established by AWS, so that my ad hoc queries do not fail.

Several of our UDFs have apparently become too large to execute on the cluster. It's a bit unclear why this is, since the volume of data occupied by card metadata is only ~15MB even by the most generous estimate. AWS does not document what the memory threshold for Python UDFs is, nor precisely what the lifecycle of Python UDFs is on the cluster. But we believe that we've been well under the limit in the past, and there are some concise steps we can take to reduce our memory footprint again. So we should switch - where possible - to SQL implementations joining against the `card` table, and we can also remove the UDFs we no longer use.

This story is complete when:
- [x] The `f_card_info` UDF (and all other unused UDFs) has been removed from the hsredshift codebase
- [x] All unused UDFs have been dropped from the production database
- [x] The `DBF_TO_CARD` dict has been modified to store only card name and cost and only include  _collectible_ cards.
- [ ] The `f_card_url` UDF has been replaced with a SQL-based implementation

**Comment by joolean** [comment]
- rewrite this UDF in SQL
- remove Python UDF dependencies on hearthstone_data
- remove any other unused Python UDFs

**Comment by beheh** [comment]
- Remove the UDF `f_card_info`
- Remove the UDF `to_pretty_decklist` - could we rework this?
- Replace the UDF `f_card_name` with a SQL based version
- Replace the UDF `f_card_url` with a version that just appends the dbf id to the cards URL
