### ISSUE TITLE
Manually Reap Redshift

### ISSUE THREAD

**Issue by amw2104** [HearthSim/hsredshift#136]
As an HSReplay.net stakeholder, I want the old data for 2017 to be archived to S3 and reaped from the cluster so that we do not run out of space.

The archived data should be placed in this bucket

https://console.aws.amazon.com/s3/buckets/hsreplaynet-redshift-archive/?region=us-east-1&tab=overview#

Using this script:

https://github.com/HearthSim/hsredshift/blob/master/scripts/sql/archive_table_template.sql

The tables that need to be archived are:
* tag_change
* block
* entity
* block_info
* choices

This story is complete when:
- [ ] The tables listed have been archived to S3 using the script
- [ ] The archived data has been deleted from Redshift using the script

**Comment by azeier** [comment]
Prepated statements (minus access key/secret): https://gist.github.com/azeier/dd981f09674d5df99f5e709838c51481

tag_change, block, entity, and block_info have been archived up to 2017-11 and choices has not been archived in 2017.
