### ISSUE TITLE
Add went_first column to player table

### ISSUE THREAD

**Issue by beheh** [HearthSim/hsredshift#138]
As an HSReplay.net data analyst I want to be able to quickly differentiate games in which a player went first, so that I can write queries and build features that can highlight differences between data from games in which the player went first compared to when they had the coin.

In order to support first/coin types of queries, we should have an easy way of detecting which player went first. We get this by adding a `went_first` column to the player turn that would be populated appropriately by the exporter looking at turn ending tag changes.

Alternative: There may be some esoteric ways of guessing who went first in pure SQL, for example by looking at number of cards in hand, we don't actually directly track a tag we could use to infer the player in say the tag_change table. In addition, this kind of logic would either need to be built as a view or copy pasted into every query that needs this functionality. Hand-writing queries is much faster.

For now, backfilling this should not be necessary, as we haven't got a specific feature to build. Whenever we decide to backfill, we can think about one of the more SQL-based ways to find out who went first. Until then we'll just start building a backlog of populated rows by getting this change done.

This story is complete, when:
- [ ] We have added a nullable boolean `went_first` column to the `player` table definition
- [ ] We have updated the exporter to find out which player went first and to make that flag available to Redshift via a `PlayerRecord` property
- [ ] We have extensive test coverage over multiple types of replays (Ranked, Adventures) that ensure the `went_first` column is populated correctly
- [ ] We have applied a migration to add the `went_first` column to the end of the player table
- [ ] We have deployed the code changes to production
- [ ] We have confirmed that new player rows are populated with the expected values for `went_first` in production

**Comment by jleclanche** [comment]
Don't you have a first_player tag?

**Comment by beheh** [comment]
It's not captured in Redshift, as we only track tags that are whitelisted there. We could add it to the whitelist, but I feel like that makes it cumbersome to quickly whip up queries if you first have to LEFT JOIN that table. It's also not like we really care about this tag changing, we only care about it's one and only state.

I'd rather have the exporter check for that tag and set a boolean flag on a player.

**Comment by jleclanche** [comment]
Sounds good -- Shall we call the column `first_player` then?

**Comment by beheh** [comment]
Now you mention it, we have a `is_first` column already :man_facepalming:
