### ISSUE TITLE
Add win count to Redshift player table

### ISSUE THREAD

**Issue by joolean** [HearthSim/hsredshift#152]
As an HSReplay.net developer, I would like to be able to build reports that include / are filtered by a player's win count in a brawl or arena run, so that I can create front-end features that depend on this value.

This story is complete when:
- [ ] The upload processing Lambda has been updated to add "wins" for each player (when available) to the `game_info` dictionary
- [ ] The player table has been altered to add a "wins" column (as a `SMALLINT`) with default value 0
- [ ] The Redshift exporter has been updated to read the "wins" column for each player and write it as the "wins" column in the player record, when available

**Comment by beheh** [comment]
Untagging queries, as not catalogue queries will be written/modified as part of this story.

**Comment by beheh** [comment]
Duplicate of #16.
