### ISSUE TITLE
Add is_first column to Redshift included_card_stats materialized view

### ISSUE THREAD

**Issue by joolean** [HearthSim/hsredshift#153]
As a HearthSim developer, I need to be able to filter included card stats by the presence of the coin (i.e., going first, going second) so that I can write queries that filter on winrate by coin status and build user-facing features that explore the impact of the coin on card inclusion winrates.

This story is complete when:
- [ ] The `included_card_stats` view has been altered to include a NULLable "is_first" column (as a BOOLEAN) to allow it to be partitioned by coin status
- [ ] The ETL queries that update the `included_card_stats_view` have been updated to write the "is_first" column
- [ ] All queries that rely on `included_card_stats` have been pinned by tests (and adjusted, as necessary) to ensure that their results remain consistent
- [ ] The trailing thirty days' worth of `included_card_stats` data has been backfilled to be partitioned by coin status

**Comment by beheh** [comment]
This is mostly a duplicate of #120, although that one specifically also mentions `deck_summary_stats`.

**Comment by beheh** [comment]
This was done in Jira.
