### ISSUE TITLE
Add deck winrate stats end point for HDT to use

### ISSUE THREAD

**Issue by amw2104** [HearthSim/hsredshift#18]
E.g. https://hsreplay.net/analytics/query/single_deck_base_winrate_by_opponent_class/?GameType=RANKED_STANDARD&RankRange=ALL&deck_id=ZrydJsC1jKZ3TpSiFWQXNg

Needs to have the overall win rate, and needs to be cached, and behind /api

**Comment by beheh** [comment]
See branch [`dev/total_win_rate`](https://github.com/hearthsim/hsredshift/compare/master...dev/total_win_rate).
