### ISSUE TITLE
Missing Rows in Redshift Replay Data for Kazakus

### ISSUE THREAD

**Issue by dtoker** [HearthSim/hsredshift#2]
Each time Kazakus is played, we expect 9 entries of information to be recorded: [3 chosen options + 6 non-chosen options]

I have found two common manifestations (they may both caused from the same issue):
1. For many games (~2-5%), when Kakazus is played, there is 1 choice entry (we expect there to be 9)

2. For many games (~45%), when Kakazus is played, there is 1 choice entry missing (we expect there to be 9, and there are only 8). From what I can find, it's typically one of the choice options with the id = 6

**Comment by dtoker** [comment]
It is possible that this is just an issue with the Query, and not Redshift. Will hopefully know more later this week from Andrew as he investigates the problem.

**Comment by beheh** [comment]
This was a general issue (#50) and has since been fixed (#53, 7463a64).
