### ISSUE TITLE
Design auto-archiving system for Redshift

### ISSUE THREAD

**Issue by amw2104** [HearthSim/hsredshift#20]
As an HSReplay.net stakeholder, I would like a technical design document on Confluence for an automated process to run at the start of each month that automatically archives old data in Redshift to S3, so that the Redshift cluster does not run out of disk space over time.

In order to prevent our Redshift COGS from growing over time we need to keep a fixed number of months of data "online" in the cluster and auto-archive older data to S3. This must apply to all tables in Redshift, both primary tables and materialized views. Currently we are archiving only a handful of tables to this S3 bucket:

https://console.aws.amazon.com/s3/buckets/hsreplaynet-redshift-archive/?region=us-east-1&tab=overview#

Using this script:

https://github.com/HearthSim/hsredshift/blob/master/scripts/sql/archive_table_template.sql

As part of this story we need a design for a tool that will archive all tables and materialized views. The number of months of data we keep online should be configurable on a per table basis, with the initial configuration being as follows:

__5 Full Months Of Historical Data Online__

e.g. If this archiving tool had run at the beginning of June it would have archived all months older than 2018, and only left January - May online.

* tag_change
* block
* entity
* block_info
* choices
* card_played_stats
* included_card_stats
* deck_summary_stats
* individual_card_stats

__25 Full Months Of Historical Data Online__

* game
* player
* rank_history
* include
* deck

__Compacted Tables__
* deck_archetype_log (this will require special compaction query based on deck_archetype_map view so that we at least one and only one log entry for each unique deck)

Additionally, the design must achieve the following requirements:
- The implemented solution is part of the hsredshift repository.
- We can configure in less then 5 minutes when the auto-archiver is scheduled to run.
- We can configure in less then 5 minutes the retention policy for each table and material view on a per table / view basis.
- We can configure in less then 5 minutes the S3 bucket that is used to store the archived data.
- We have correct handling for deck_archetype_log type compactions.
- We have a design for how we will be protected from executing any DELETE statements in a scenario where the UNLOAD statement was only partially successful.
- When the archiver runs, if there is a table in Redshift that does not have an archive policy defined and the table name does not have the prefix volt_tt*, redshift_auto_health_check*, stage_*, or pre_stage_* then an alert gets raised to notify us that we might have recently introduced a table that could be subject to unbounded growth.
- We have a design for a deadman alert in case the auto-archiver fails to launch and run when it's supposed to.
- We have a design for an alert in case the total storage used on the cluster exceeds 70%.
- The archiver design has a dry run mode where it prints what it is about to do, including all of the raw SQL statements to be run so that an engineer could take them and run them by hand if desired.
- We have identified the critical elements that will need test coverage.
- In the design, if the archiver has not been run for multiple months it will archive all the months that it needs to in order to bring the cluster into compliance with the archiving policy.
- The design document defines where the process will be deployed to in production and how it will be configured.

This story is complete when:
- [ ] There is a technical design document in Confluence that covers all of the above requirements
- [ ] The full set of stories has been written which will be needed to implement the archiver
- [ ] Reading the technical design document makes it easy for any engineer to estimate the associated implementation stories

**Comment by azeier** [comment]
Resize in progress. This is no longer critical and can be done later.

**Comment by joolean** [comment]
- [ ] Decide whether the tool is a command-line tool or some other type of application
- [ ] Decide whether the tool is stateless or if there is state to maintain (and if so where it is to be persisted)
- [ ] Identify queries to be run 
- [ ] Define identify-backup-verify-delete flow
- [ ] Propose an idempotency strategy

**Comment by joolean** [comment]
Capture state from Redshift using GROUP BY game date month, ORDER BY game date month - so you can see which days have data.
