### ISSUE TITLE
Add a single card stats endpoint similar to our single_deck_stats endpoint

### ISSUE THREAD

**Issue by amw2104** [HearthSim/hsredshift#27]
It should include the following 4 data points: 
- Popularity In Decks
- Win Rate Of Decks Running It (drawn vs played winrate)
- Avg Copies Run In Decks
- Total Number Of Decks Running It

For neutral cards it will provide the blended values across all player classes that run it.

**Comment by beheh** [comment]
We'll be using this for the Twitch Extension.

**Comment by beheh** [comment]
Done!
