### ISSUE TITLE
Convert card_included_popularity_report to use a materialized view

### ISSUE THREAD

**Issue by amw2104** [HearthSim/hsredshift#28]

**Comment by amw2104** [comment]
This will fix: https://sentry.io/hearthsim/hsreplaynet/issues/259420034/

This query is timing out repeatedly and creating immense amounts of cluster thrashing.

**Comment by beheh** [comment]
We didn't need a materialized view after all - it's much more efficient with a reworked `include` table. See 2ea02921f63b5e791622dc5b62a05b8ec01be5a4...321b47ca4236b868454145a4b3810915d467c443.
