### ISSUE TITLE
Implement a Postgres test layer

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/hsredshift#33]
I'd like to implement a postgres layer in order to help testing queries on Travis.

Goals:

1. Make sure the schema definitions can be used to generate postgres tables
2. Rework the firehose exporter to allow plugging sqlalchemy into it and let it generate insert statements
3. Add some tests that export to a local postgres database; test our queries with that output.

**Comment by amw2104** [comment]
This is a 48 hour design spike.

**Comment by jleclanche** [comment]
All done, tests are even running on Travis!
