### ISSUE TITLE
Update tests that depend on entity_state to use entity table instead

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/hsredshift#49]

**Comment by amw2104** [comment]
All the tests should still be working or able to be ported to the new tables, with the following exceptions:

1) The following tests can no longer assert zone_position but all other asserts are still possible:
* test_zone_transition_created
* test_zone_transition_play
* test_zone_transition_bounced
* test_entity_state_double_kazakus_potion_created
* test_entity_state_kazakus_choices
* test_zone_transition_secret_played
* test_zone_transition_drawn_played

2) The following tests should be removed:
* test_tag_value_changes - Can't really be supported anymore
* test_opposing_zerus_t21_gamestate -  Can't really be supported anymore

3) The following tests need modification:
* test_exporter_on_opposing_zerus - Can longer assert record counts on entity_state or zerus behavior at the end. We should add assertions for record counts for the new entity and tag_change records.
* test_exporter_on_friendly_zerus - We need to rewrite this test to make sure that for Zerus the entity record that we create has the dbf of the final card that zerus gets played as (Animated Armor) but that we properly set the transformed_from_card field to indicate the entity was originally zerus. We also need to assert that is_initial_entity = True.

**Comment by jleclanche** [comment]
I double checked for noble sacrifice and we have no concept of before/after block anymore so the noble sacrifice test doesn't have enough state.
