### ISSUE TITLE
Reconsider distribution style of include table

### ISSUE THREAD

**Issue by beheh** [HearthSim/hsredshift#51]
Running the [diagnostic query](http://docs.aws.amazon.com/redshift/latest/dg/diagnostic-queries-for-query-tuning.html#identify-tables-with-data-skew-or-unsorted-rows) we're getting a skew of >1500 for the `include` table. Amazon recommends to consider modifying the distribution style if the skew is above 4.00.

Currently the table is partitioned with the [distribution style](http://docs.aws.amazon.com/redshift/latest/dg/c_choosing_dist_sort.html) `ALL`. It is recommended to use this distribution style for relatively slow moving tables, and in fact the only other table we're using it for are `card` and `deck_archetype`. Since we've reworked the way the include view works (with it being updated evey single day) we should probably reevaluate the distribution strategy.

**Comment by amw2104** [comment]
Agreed.

**Comment by joolean** [comment]
Closing for now - there doesn't seem to be a distribution style (key or even) that's a better fit.
