### ISSUE TITLE
Rework payload of head-to-head matchups endpoint

### ISSUE THREAD

**Issue by beheh** [HearthSim/hsredshift#57]
@beheh commented on [Tue Jun 27 2017](https://github.com/HearthSim/HSReplay.net/issues/351)

**Comment by beheh** [comment]
@azeier What did we want here again?

**Comment by azeier** [comment]
This happened with https://github.com/HearthSim/hsredshift/commit/2c5033fb915597c1f943ca5cddc06112d6804249
