### ISSUE TITLE
Switch to a soft-delete pattern for query flushing

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/hsredshift#69]
By default, instead of straight up deleting queries from the Redis query cache, we should be setting them to `stale = true` or some such, so that the cached result can still be accessed but a fresh query is run anyway.

We should also be able to force delete things though, in case bad data gets into the cache.

**Comment by amw2104** [comment]
Done via 72b2423315f458dfefa989c62b53dc9b2479099d
